
setup:
	python3 -m venv ./venv
	source venv/bin/activate
	pip3 install -r requirements.txt

install:
	pip3 install -r requirements.txt

freeze:
	pip3 freeze > requirements.txt

start:
	jupyter notebook

activate:
	source venv/bin/activate
