version: "3"
services:
  dynamodb:
    image: public.ecr.aws/aws-dynamodb-local/aws-dynamodb-local:latest
    ports:
      - "8000:8000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          '[ "$(curl -s -o /dev/null -I -w ''%{http_code}'' http://localhost:8000)" == "400" ]',
        ]
      interval: 2s
      timeout: 2s
      retries: 3
    restart: always

  app:
    build: .
    ports:
      - "443:443"
      - "8443:8443"
    environment:
      APP_NAME: "grpc-chagring-location-service-local"
      BOOT_PROFILE_ACTIVE: "dc-local"
      DYNAMOLOCAL_HOST: "dynamodb"
      DYNAMOLOCAL_PORT: 8000
      AWS_ACCESS_KEY_ID: "test"
      AWS_SECRET_ACCESS_KEY: "test"
      AWS_REGION: "eu-west-1"
    volumes:
      - "./config/db/local/:/service/config/db/local"
    depends_on:
      dynamodb:
        condition: service_healthy
        restart: true
