app:
  name: ${APP_NAME}
  env: ${APP_ENV}
  profile: ${BOOT_PROFILE_ACTIVE}

grpc:
  server:
    port: 443
  proxy:
    port: 8443
  ssl:
    enabled: false
    cert_path: "cert/grpc-cert.pem"
    key_path: "cert/grpc-key.pem"
    ca_path: "cert/ca-cert.pem"

aws:
  config:
    region: ${AWS_REGION}
    account: ${ACCOUNT_ID}
  dynamodb:
    poi_table_name: ${POI_TABLE_NAME}

logging:
  level: "dev"
  env: "${APP_ENV}"
  host: ${HOSTNAME}
  app_name: ${APP_NAME}
  region: eu-west-1
  account: ${ACCOUNT_ID}
  team_name: my-team
