grpc:
  ssl:
    enabled: true
  secret: "test"

aws:
  dynamodb:
    endpoint_override:
      enabled: true
      host: ${DYNAMOLOCAL_HOST}
      port: ${DYNAMOLOCAL_PORT}
    create_init_table: true
    poi_table_name: poi_table_local

logging:
  level: "prod"
